### ISSUE TITLE
Reasons why this is crashing

### ISSUE THREAD

**Issue by ghost** [josephsmoyer/Phase10#1]
1) P10LocalGame tries to initialize a state using the players object, but LocalGame does not set the players object until its start(GamePlayer[] players) method is called. GameMainActivity calls createLocalGame() on line 266, but calls game.start(players) on line 333. So when a new P10State(players.length) is created, players is null and players.length does not exist.

2) Something about Card.initImages(activity), line 112 in P10HumanPlayer, is funky. Looking at it now.

**Comment by ghost** [comment]
```
11-17 22:02:27.883 21910-21910/edu.up.cs301.game I/cardImages: length: 5
11-17 22:02:29.563 21910-21910/edu.up.cs301.game I/cardImagesI: [0] length: 12
11-17 22:02:50.828 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][0]
11-17 22:02:51.890 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][1]
11-17 22:02:52.756 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][2]
11-17 22:02:53.627 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][3]
11-17 22:02:54.528 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][4]
11-17 22:02:55.473 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][5]
11-17 22:03:07.897 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][6]
11-17 22:03:07.918 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][7]
11-17 22:03:07.936 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][8]
11-17 22:03:07.954 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][9]
11-17 22:03:07.973 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][10]
11-17 22:03:07.992 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [0][11]
11-17 22:03:07.993 21910-21910/edu.up.cs301.game I/cardImagesI: [1] length: 12
11-17 22:03:08.011 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][0]
11-17 22:03:08.031 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][1]
11-17 22:03:08.052 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][2]
11-17 22:03:08.071 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][3]
11-17 22:03:08.090 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][4]
11-17 22:03:08.108 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][5]
11-17 22:03:08.126 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][6]
11-17 22:03:08.145 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][7]
11-17 22:03:08.164 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][8]
11-17 22:03:08.182 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][9]
11-17 22:03:08.201 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][10]
11-17 22:03:08.219 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [1][11]
11-17 22:03:08.219 21910-21910/edu.up.cs301.game I/cardImagesI: [2] length: 12
11-17 22:03:08.237 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][0]
11-17 22:03:08.255 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][1]
11-17 22:03:08.273 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][2]
11-17 22:03:08.294 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][3]
11-17 22:03:08.313 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][4]
11-17 22:03:08.330 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][5]
11-17 22:03:08.348 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][6]
11-17 22:03:08.366 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][7]
11-17 22:03:08.385 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][8]
11-17 22:03:08.403 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][9]
11-17 22:03:08.422 21910-21910/edu.up.cs301.game I/cardImagesIJ: [i][j] = [2][10]
11-17 22:03:08.426 21910-21910/edu.up.cs301.game I/art: Waiting for a blocking GC Alloc
11-17 22:03:08.428 21910-21921/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.428 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.428 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.431 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.438 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.438 21910-21910/edu.up.cs301.game I/art: Alloc partial concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 119us total 6.410ms
11-17 22:03:08.438 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.449 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.449 21910-21910/edu.up.cs301.game I/art: Alloc concurrent mark sweep GC freed 5(152B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 166us total 10.386ms
11-17 22:03:08.449 21910-21910/edu.up.cs301.game I/art: Forcing collection of SoftReferences for 5MB allocation
11-17 22:03:08.449 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.459 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.459 21910-21910/edu.up.cs301.game I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 131us total 10.054ms
11-17 22:03:08.459 21910-21910/edu.up.cs301.game W/art: Throwing OutOfMemoryError "Failed to allocate a 5600012 byte allocation with 602712 free bytes and 588KB until OOM"
11-17 22:03:08.459 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.459 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.462 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.468 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.468 21910-21910/edu.up.cs301.game I/art: Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 112us total 6.223ms
11-17 22:03:08.468 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.479 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.479 21910-21910/edu.up.cs301.game I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 111us total 10.859ms
11-17 22:03:08.479 21910-21910/edu.up.cs301.game I/art: Forcing collection of SoftReferences for 5MB allocation
11-17 22:03:08.479 21910-21910/edu.up.cs301.game I/art: Starting a blocking GC Alloc
11-17 22:03:08.489 21910-21910/edu.up.cs301.game I/art: Clamp target GC heap from 207MB to 192MB
11-17 22:03:08.489 21910-21910/edu.up.cs301.game I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 134us total 9.756ms
11-17 22:03:08.489 21910-21910/edu.up.cs301.game W/art: Throwing OutOfMemoryError "Failed to allocate a 5600012 byte allocation with 602712 free bytes and 588KB until OOM"
11-17 22:03:08.490 21910-21910/edu.up.cs301.game D/skia: --- allocation failed for scaled bitmap
11-17 22:03:08.490 21910-21910/edu.up.cs301.game D/AndroidRuntime: Shutting down VM
11-17 22:03:08.497 21910-21910/edu.up.cs301.game E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: edu.up.cs301.game, PID: 21910
                                                                   java.lang.OutOfMemoryError: Failed to allocate a 5600012 byte allocation with 602712 free bytes and 588KB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
                                                                       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
                                                                       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:478)
                                                                       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:508)
                                                                       at edu.up.cs301.card.Card.initImages(Card.java:235)
                                                                       at edu.up.cs301.phase10.P10HumanPlayer.setAsGui(P10HumanPlayer.java:112)
                                                                       at edu.up.cs301.game.GameHumanPlayer.gameSetAsGui(GameHumanPlayer.java:113)
                                                                       at edu.up.cs301.game.GameMainActivity.launchGame(GameMainActivity.java:321)
                                                                       at edu.up.cs301.game.GameMainActivity.startGame(GameMainActivity.java:533)
                                                                       at edu.up.cs301.game.GameMainActivity.onClick(GameMainActivity.java:521)
                                                                       at android.view.View.performClick(View.java:5637)
                                                                       at android.view.View$PerformClick.run(View.java:22429)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-17 22:03:14.636 21910-21921/edu.up.cs301.game I/art: Clamp target GC heap from 199MB to 192MB
```

It stops at the place where it would initialize y_12.png. Nothing seems wrong.

**Comment by ghost** [comment]
I think I'm going to try making the cards smaller to see if it's just that the images take up too much memory.

**Comment by ghost** [comment]
Yeah, it's the size of the images.
